language: node_js
node_js:
- 8
script:
- export REPO=callthemonline/simple-call-server
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -f docker/Dockerfile -t $REPO:$COMMIT .
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: Et5CT1DiWIUmUXHBpuJ3pQaA0hNZMsxKMjwvEELtxdoyo45dFbpI5y5qY/9Zh5oPuyxfRjtDfdROHQyueNbuqv02Fm1QMUAoM6cAx3Xeb46CwLxZzEu5sdKwXlr++T4QNQzUt5xEl19sx3UMu3xcicaTlU/+GpCAjukik4VUuPrqOSq4U/w+HQjtafKMI9TCh7EgnMy5oTZxim6lipPrg2FKeOkmsFNJskkb22by7kx/GDiTsWanbDI87Klxv6jb+gNWR9TrHHjN8t9MMtG+d0n2YPAZ+EmYOf2m21VwEshbQ/xWJnVZHYZ6a1busFTq+Y9NaSofWxZ/4TSZySoXSYSDcJMGO5AMFNp/5cnT2DDGMhlSjoohbc5ShDOMwAx19lv/OYET4esMtl+UHi8ANYADSDmqYwHDA78Dq6tNYL4HJyacAgOhU6fWwrGyVuQqL2aG1GJiZfUBaJAeD5HfLs4CQhKuXGYbtlHvjNjxfTjVwcKkMiIGE4LpAimltjVaA66hNWb9GLdyaQsccTwICPleNECSwhnzoNrHzj6ekTY79qTUv8ZZGInp5xM4+pGVYpoBDisI/S5yzd1pNMQiOHvWb3oUVytK05iCmF4Tz8xPv83NFwgTrcFAweJtrGxl78CJJ2BVdK7C9SeMbs3YSr/vLwrvUrLF3mDl7dITHrA=
  - secure: z5RG/YyWQobIy6hIvVEobtzgG+cwKEFgaHu1qPNs7KmOTAhQpDksm2xIYfBalVHQt2R9I6OEyzvz7Fh0de87FW2gL0txvtAhGJzxJN+5/R8H9lJ1JPU1cMdkDJecBFNYm7Pu4q8xtL4nTfiQaWpSoaOO/9aQUIzyyrS6bHw4v0Ss/D35MvqCjK3dGx19osAjT/0nmwJYNPMftm5tntZGkYa2I4tR8JKYBwe/jDoztWASZWIrYVwpVvCIMwp7BpbTBTQsAHeLTMIZp6NMIXjh7VB9vgmG/yfBmx6Jom8rSNvOzEIA0wqukpO09zZsufPIXH4ekPHTNoWLTf6axjhQziehEhZ0ImjS1EJ02gPQgu9YwFYylgJdXIQcclrVX5BGgVAdC5vjfUVDyfiVWOPIWGNWgHRF/CqSUzmhu8Vm6MW7QD0zQoB5gc0POledqqvl5wJ1vGpj/GYG8WOHDHf3+pe78mRFkXuVXudZZDVxVEWsLxxE8tFUPdShX4XM+ZuQHfhSzvSZ0Tb+SxmBFDeXjeGCOd+MTwbZ1Ja+r67jR59BWwtrN+R4OieLmJqtN9O8h+1go7XJ9m4jwU1SlaEeA5a7ld8XcfwBmwkvmxnAd5CPq5EKIDMINrHPRZuZY+kxJvrkfF1uRFUShjh/eBWpMFdEQzHr1CE5j2OxFANkYZ8=
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker push $REPO
